import React, { useState, useRef } from 'react';
import { useApp } from '../context/AppContext';

import { exportTextFile, exportPDF } from '../utils/export';

export const ResumeBuilder = () => {
  const { projects, education, experiences, saveResume, setCurrentView } = useApp();

  const [step, setStep] = useState(1);
  const [jobPosting, setJobPosting] = useState('');
  const [resumeTitle, setResumeTitle] = useState('');
  const [selectedProjects, setSelectedProjects] = useState([]);
  const [selectedEducation, setSelectedEducation] = useState([]);
  const [selectedExperiences, setSelectedExperiences] = useState([]);
  const [customResume, setCustomResume] = useState(null);
  const resumeRef = useRef();
  // Markdown generator
  function resumeToMarkdown(resume) {
    if (!resume) return '';
    let md = `# ${resume.title || 'Resume'}\n`;
    if (resume.jobPosting) md += `\n> **Job Posting:** ${resume.jobPosting}\n`;
    if (resume.projects?.length) {
      md += `\n## Projects\n`;
      resume.projects.forEach(p => {
        md += `- **${p.title}**: ${p.description || ''}`;
        if (p.technologies) md += `\n  - Technologies: ${p.technologies}`;
        if (p.highlights?.length) md += `\n  - Highlights: ${p.highlights.join('; ')}`;
        md += '\n';
      });
    }
    if (resume.education?.length) {
      md += `\n## Education\n`;
      resume.education.forEach(e => {
        md += `- **${e.school || e.institution}**: ${e.degree || ''}`;
        if (e.field) md += ` in ${e.field}`;
        if (e.startYear || e.endYear) md += ` (${e.startYear || ''}-${e.endYear || ''})`;
        md += '\n';
      });
    }
    if (resume.experiences?.length) {
      md += `\n## Experiences\n`;
      resume.experiences.forEach(x => {
        md += `- **${x.position || x.title}** at ${x.company || ''}`;
        if (x.startDate || x.endDate) md += ` (${x.startDate || ''}-${x.endDate || ''})`;
        if (x.description) md += `\n  - ${x.description}`;
        if (x.achievements?.length) md += `\n  - Achievements: ${x.achievements.join('; ')}`;
        md += '\n';
      });
    }
    return md;
  }
  // Export handlers
  const handleExportMarkdown = () => {
    if (customResume) {
      exportTextFile((customResume.title || 'resume') + '.md', resumeToMarkdown(customResume));
    }
  };

  const handleExportPDF = async () => {
    if (resumeRef.current) {
      await exportPDF(resumeRef.current, (customResume?.title || 'resume') + '.pdf');
    }
  };

  const handleSelectProject = (projectId) => {
    setSelectedProjects((prev) =>
      prev.includes(projectId)
        ? prev.filter((id) => id !== projectId)
        : [...prev, projectId]
    );
  };

  const handleSelectEducation = (eduId) => {
    setSelectedEducation((prev) =>
      prev.includes(eduId) ? prev.filter((id) => id !== eduId) : [...prev, eduId]
    );
  };

  const handleSelectExperience = (expId) => {
    setSelectedExperiences((prev) =>
      prev.includes(expId) ? prev.filter((id) => id !== expId) : [...prev, expId]
    );
  };

  const handleNextToCustomize = () => {
    const selectedProjectsData = projects.filter((p) => selectedProjects.includes(p._id));
    
    // Auto-generate skills from project technologies
    const autoGeneratedSkills = selectedProjectsData
      .map(p => p.technologies)
      .filter(Boolean)
      .flatMap(t => t.split(',').map(s => s.trim()))
      .filter((v, i, a) => a.indexOf(v) === i)
      .join(', ');

    const resume = {
      title: resumeTitle,
      jobPosting,
      skills: autoGeneratedSkills,
      projects: selectedProjectsData.map(p => ({ ...p })),
      education: education.filter((e) => selectedEducation.includes(e._id)).map(e => ({ ...e })),
      experiences: experiences.filter((e) => selectedExperiences.includes(e._id)).map(e => ({ ...e })),
    };
    setCustomResume(resume);
    setStep(3);
  };

  const handleUpdateResumeField = (section, itemId, field, value) => {
    setCustomResume((prev) => ({
      ...prev,
      [section]: prev[section].map((item) =>
        item._id === itemId ? { ...item, [field]: value } : item
      ),
    }));
  };

  const handleUpdateResumeArrayField = (section, itemId, field, value) => {
    setCustomResume((prev) => ({
      ...prev,
      [section]: prev[section].map((item) =>
        item._id === itemId
          ? { ...item, [field]: value.split('\n').filter((v) => v.trim()) }
          : item
      ),
    }));
  };

  const handleSaveResume = () => {
    saveResume(customResume);
    handleReset();
    setCurrentView('saved');
  };

  const handleReset = () => {
    setStep(1);
    setJobPosting('');
    setResumeTitle('');
    setSelectedProjects([]);
    setSelectedEducation([]);
    setSelectedExperiences([]);
    setCustomResume(null);
  };

  return (
    <div className="resume-builder">
      <div className="builder-header">
        <h2>Build Custom Resume</h2>
        <div className="progress-steps">
          <div className={`step ${step >= 1 ? 'active' : ''}`}>1. Job Info</div>
          <div className={`step ${step >= 2 ? 'active' : ''}`}>2. Select Items</div>
          <div className={`step ${step >= 3 ? 'active' : ''}`}>3. Customize</div>
        </div>
      </div>

      {step === 1 && (
        <div className="builder-step">
          <h3>Step 1: Job Information</h3>
          <div className="form-group">
            <label>Resume Title</label>
            <input
              type="text"
              placeholder="e.g., Software Engineer at Google"
              value={resumeTitle}
              onChange={(e) => setResumeTitle(e.target.value)}
            />
          </div>
          <div className="form-group">
            <label>Job Posting Description (Optional)</label>
            <textarea
              placeholder="Paste the job description here to reference while selecting items..."
              value={jobPosting}
              onChange={(e) => setJobPosting(e.target.value)}
              rows="8"
            />
          </div>
          <button
            className="btn-primary"
            onClick={() => setStep(2)}
            disabled={!resumeTitle.trim()}
          >
            Next: Select Items
          </button>
        </div>
      )}

      {step === 2 && (
        <div className="builder-step">
          <h3>Step 2: Select Relevant Items</h3>

          {jobPosting && (
            <div className="job-reference">
              <h4>Job Description Reference:</h4>
              <div className="job-text">{jobPosting}</div>
            </div>
          )}

          <div className="selection-section">
            <h4>Projects ({selectedProjects.length} selected)</h4>
            {projects.length === 0 ? (
              <p className="empty-message">No projects available. Add some in the Master List!</p>
            ) : (
              <div className="selection-grid">
                  {projects.map((project) => (
                    <div
                      key={project._id}
                      className={`selection-card ${
                        selectedProjects.includes(project._id) ? 'selected' : ''
                      }`}
                      onClick={() => handleSelectProject(project._id)}
                    >
                      <input
                        type="checkbox"
                        checked={selectedProjects.includes(project._id)}
                        readOnly
                      />
                      <div className="selection-content">
                        <h5>{project.title}</h5>
                        <p>{project.description}</p>
                      </div>
                    </div>
                  ))}
              </div>
            )}
          </div>

          <div className="selection-section">
            <h4>Education ({selectedEducation.length} selected)</h4>
            {education.length === 0 ? (
              <p className="empty-message">No education entries available. Add some in the Master List!</p>
            ) : (
              <div className="selection-grid">
                  {education.map((edu) => (
                    <div
                      key={edu._id}
                      className={`selection-card ${
                        selectedEducation.includes(edu._id) ? 'selected' : ''
                      }`}
                      onClick={() => handleSelectEducation(edu._id)}
                    >
                      <input
                        type="checkbox"
                        checked={selectedEducation.includes(edu._id)}
                        readOnly
                      />
                      <div className="selection-content">
                        <h5>{edu.institution}</h5>
                        <p>{edu.degree}</p>
                      </div>
                    </div>
                  ))}
              </div>
            )}
          </div>

          <div className="selection-section">
            <h4>Experiences ({selectedExperiences.length} selected)</h4>
            {experiences.length === 0 ? (
              <p className="empty-message">No experiences available. Add some in the Master List!</p>
            ) : (
              <div className="selection-grid">
                  {experiences.map((exp) => (
                    <div
                      key={exp._id}
                      className={`selection-card ${
                        selectedExperiences.includes(exp._id) ? 'selected' : ''
                      }`}
                      onClick={() => handleSelectExperience(exp._id)}
                    >
                      <input
                        type="checkbox"
                        checked={selectedExperiences.includes(exp._id)}
                        readOnly
                      />
                      <div className="selection-content">
                        <h5>{exp.position}</h5>
                        <p>{exp.company}</p>
                      </div>
                    </div>
                  ))}
              </div>
            )}
          </div>

          <div className="step-actions">
            <button className="btn-secondary" onClick={() => setStep(1)}>
              Back
            </button>
            <button
              className="btn-primary"
              onClick={handleNextToCustomize}
              disabled={
                selectedProjects.length === 0 &&
                selectedEducation.length === 0 &&
                selectedExperiences.length === 0
              }
            >
              Next: Customize Resume
            </button>
          </div>
        </div>
      )}

      {step === 3 && customResume && (
        <div className="builder-step">
          <h3>Step 3: Customize Your Resume</h3>
          <p className="step-description">Edit the content below to tailor it for this specific job.</p>

          <div className="customize-section">
            <h4>Skills (Optional)</h4>
            <textarea
              value={customResume.skills || ''}
              onChange={(e) =>
                setCustomResume((prev) => ({ ...prev, skills: e.target.value }))
              }
              placeholder="Enter skills separated by commas (e.g., JavaScript, React, Node.js)"
              rows="3"
              style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid #ddd' }}
            />
          </div>

          {customResume.projects.length > 0 && (
            <div className="customize-section" ref={resumeRef}>
              <h4>Projects</h4>
              {customResume.projects.map((project) => (
                <div key={project._id} className="customize-card">
                  <input
                    type="text"
                    value={project.title}
                    onChange={(e) =>
                      handleUpdateResumeField('projects', project._id, 'title', e.target.value)
                    }
                    className="edit-title"
                  />
                  <textarea
                    value={project.description}
                    onChange={(e) =>
                      handleUpdateResumeField('projects', project._id, 'description', e.target.value)
                    }
                    rows="2"
                  />
                  <input
                    type="text"
                    value={project.technologies}
                    onChange={(e) =>
                      handleUpdateResumeField('projects', project._id, 'technologies', e.target.value)
                    }
                    placeholder="Technologies"
                  />
                  <textarea
                    value={project.highlights?.join('\n') || ''}
                    onChange={(e) =>
                      handleUpdateResumeArrayField('projects', project._id, 'highlights', e.target.value)
                    }
                    placeholder="Highlights (one per line)"
                    rows="3"
                  />
                </div>
              ))}
            </div>
          )}

          {customResume.education.length > 0 && (
            <div className="customize-section">
              <h4>Education</h4>
              {customResume.education.map((edu) => (
                <div key={edu._id} className="customize-card">
                  <input
                    type="text"
                    value={edu.institution}
                    onChange={(e) =>
                      handleUpdateResumeField('education', edu._id, 'institution', e.target.value)
                    }
                    className="edit-title"
                  />
                  <input
                    type="text"
                    value={edu.degree}
                    onChange={(e) =>
                      handleUpdateResumeField('education', edu._id, 'degree', e.target.value)
                    }
                  />
                  <input
                    type="text"
                    value={edu.field || ''}
                    onChange={(e) =>
                      handleUpdateResumeField('education', edu._id, 'field', e.target.value)
                    }
                    placeholder="Field of Study"
                  />
                </div>
              ))}
            </div>
          )}

          {customResume.experiences.length > 0 && (
            <div className="customize-section">
              <h4>Experiences</h4>
              {customResume.experiences.map((exp) => (
                <div key={exp._id} className="customize-card">
                  <input
                    type="text"
                    value={exp.position}
                    onChange={(e) =>
                      handleUpdateResumeField('experiences', exp._id, 'position', e.target.value)
                    }
                    className="edit-title"
                  />
                  <input
                    type="text"
                    value={exp.company}
                    onChange={(e) =>
                      handleUpdateResumeField('experiences', exp._id, 'company', e.target.value)
                    }
                  />
                  <textarea
                    value={exp.description}
                    onChange={(e) =>
                      handleUpdateResumeField('experiences', exp._id, 'description', e.target.value)
                    }
                    rows="2"
                  />
                  <textarea
                    value={exp.achievements?.join('\n') || ''}
                    onChange={(e) =>
                      handleUpdateResumeArrayField('experiences', exp._id, 'achievements', e.target.value)
                    }
                    placeholder="Achievements (one per line)"
                    rows="3"
                  />
                </div>
              ))}
            </div>
          )}

          <div className="step-actions">
            <button className="btn-secondary" onClick={() => setStep(2)}>
              Back to Selection
            </button>
            <button className="btn-primary" onClick={handleSaveResume}>
              Save Resume
            </button>
            <button className="btn-secondary" onClick={handleReset}>
              Start Over
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
